[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-build-script-utils'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[[bin]]
name = 'substrate-runtime-contract-sample'
path = 'src/main.rs'
[profile.release]
panic = 'unwind'

[workspace]
members = ['runtime']

[dependencies]
derive_more = '0.15.0'
futures = '0.3.1'
log = '0.4.8'
parking_lot = '0.9.0'
tokio = '0.1.22'
trie-root = '0.15.2'

[dependencies.aura]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.contracts]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-contracts'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.aura-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura-primitives'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-basic-authorship'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.ctrlc]
features = ['termination']
version = '3.1.3'

[dependencies.futures01]
package = 'futures'
version = '0.1.29'

[dependencies.grandpa]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-finality-grandpa'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.grandpa-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-finality-grandpa-primitives'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-network'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.runtime]
package = 'substrate-runtime-contract-sample-runtime'
path = 'runtime'

[dependencies.sr-io]
git = 'https://github.com/paritytech/substrate.git'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.sr-primitives]
git = 'https://github.com/paritytech/substrate.git'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate.git'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.substrate-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate.git'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool'
rev = '77e681fb8b9c1e98ef1441bcc648e40ee36dac41'

[package]
authors = ['Anonymous']
build = 'build.rs'
edition = '2018'
name = 'substrate-runtime-contract-sample'
version = '2.0.0'
